apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: jobportal-prod
  labels:
    app: jobportal
    component: monitoring
    monitor: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      name: http
