apiVersion: v1
kind: ConfigMap
metadata:
  name: jobportal-config
  namespace: jobportal-prod
  labels:
    app: jobportal
    component: config
data:
  # Global
  NODE_ENV: "production"

  # Database connection params (host will be overridden by service discovery)
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "jobportal"

  # Service-specific DB names
  USER_SERVICE_DB: "user_db"
  JOB_SERVICE_DB: "job_db"
  APPLICATION_SERVICE_DB: "application_db"
  NOTIFICATION_SERVICE_DB: "notification_db"

  # Postgres container init
  POSTGRES_USER: "jobportal"
  POSTGRES_DB: "postgres"

  # RabbitMQ
  RABBITMQ_USER: "jobportal"

  # Service URLs (internal)
  USER_SERVICE_URL: "http://user-service:3000"
  JOB_SERVICE_URL: "http://job-service:3001"
  APPLICATION_SERVICE_URL: "http://application-service:3002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3003"
  GATEWAY_URL: "http://gateway:80"

  # Grafana
  GF_SECURITY_ADMIN_USER: "admin"

  # Prometheus
  PROMETHEUS_URL: "http://prometheus:9090"
