apiVersion: v1
kind: Secret
metadata:
  name: jobportal-secrets
  namespace: jobportal-prod
  labels:
    app: jobportal
    component: secrets
type: Opaque
data:
  JWT_SECRET: eW91ci02NC1jaGFyYWN0ZXItaGV4LXNlY3JldC1oZXJlLW11c3QtYmUtYXQtbGVhc3QtNjQtY2hhcnMtbG9uZy0xMjM0NTY3ODkwYWJjZGVm
  DB_PASSWORD: am9icG9ydGFsX3NlY3VyZV9wYXNzd29yZF8yMDI0
  POSTGRES_PASSWORD: am9icG9ydGFsX3NlY3VyZV9wYXNzd29yZF8yMDI0
  RABBITMQ_PASS: am9icG9ydGFsX3NlY3VyZV9wYXNzd29yZF8yMDI0
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW5fcGFzc3dvcmRfMjAyNA==
