apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: jobportal-prod
  labels:
    app: jobportal
    component: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - port: 3000
      targetPort: 3000
      name: http
