apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: jobportal-prod
  labels:
    app: jobportal
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        component: frontend
    spec:
      containers:
        - name: app
          image: jobportal/app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: jobportal-config
          env:
            - name: GATEWAY_URL
              value: "http://gateway:80"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
