apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: jobportal-prod
  labels:
    app: jobportal
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80
      name: http
