apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: jobportal-prod
  labels:
    app: jobportal
    component: job-service
spec:
  type: ClusterIP
  selector:
    app: job-service
  ports:
    - port: 3001
      targetPort: 3001
      name: http
