apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: jobportal-prod
  labels:
    app: jobportal
    component: application-service
spec:
  type: ClusterIP
  selector:
    app: application-service
  ports:
    - port: 3002
      targetPort: 3002
      name: http
